name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    
      - 
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      


      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and not push Docker image
        env:
          REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          docker buildx build \
            --build-arg USER='devops' \
            --build-arg REPO='https://bitbucket.org/devsu/demo-devops-python.git' \
            --build-arg PORT=8000 \
            -t $REPO .

      - 
        name: Run Unit Tests
        env:
          REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: docker run $REPO py manage.py test
