name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  deploy-docker-hub:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        id: push_image
        run: |
          docker build \
            --build-arg USER='ultron' \
            --build-arg REPO='https://bitbucket.org/devsu/demo-devops-python.git' \
            --build-arg PORT=8000 \
            -t davidmartinezb1/devops-solution:latest .
          docker push davidmartinezb1/devops-solution:latest
  
  deploy-kubernete:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Apply ConfigMap
        id: apply_config_map
        run: kubectl apply -f kubernetes/configmap.yml

      - name: Apply Secret
        id: apply_secret
        run: kubectl apply -f kubernetes/secret.yml

      - name: Deploy to Kubernetes
        id: deploy_kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/services.yml
          kubectl apply -f kubernetes/ingress.yml
