name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    needs: CI
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3

      - 
        name: Push Docker Image to Docker Hub
        id: push_image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag ${{ needs.CI.outputs.REPO }}:latest ${{ secrets.DOCKERHUB_REPO }}:latest
          docker push ${{ secrets.DOCKERHUB_REPO }}:latest
      
      - 
        name: Deploy to Kubernetes
        id: deploy_kubernetes
        run: echo "TODO Add steps to deploy the Docker image to Kubernetes"