name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
    
      - 
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      


      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and not push Docker image
        run: |
          docker buildx build \
            --build-arg USER='devops' \
            --build-arg REPO='https://bitbucket.org/devsu/demo-devops-python.git' \
            --build-arg PORT=8000 \
            --load \
            -t $REPO .
      
      - 
        name: Run Unit Tests
        run: |
          docker run $REPO python3 manage.py test
      
      - 
        name: Static Code Analysis
        run: 
          docker run $REPO pylint manage.py
        env:
          CI: false

      - name: Code Coverage
        run: docker run $REPO coverage run --source=manage.py -m pytest && coverage report 

      - name: Run Bandit for security analysis
        run: docker run $REPO ~/.local/bin/bandit -r .
