name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          docker build \
            --build-arg USER=devops \
            --build-arg REPO=https://bitbucket.org/devsu/demo-devops-python.git \
            --build-arg PORT=8000 \
            -t $REPO .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag $REPO $DOCKER_USERNAME/$REPO
          docker push $DOCKER_USERNAME/$REPO

      - name: Vulnerability scan
        uses: anchore/scan-action@v2
        with:
          image-reference: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
